(library
 (name tokenizer_diff)
 (wrapped false)
 (modules tokenizer_diff)
 (libraries markup markup_ref_tokenizer))

(test
 (name tokenizer_diff_test)
 (modules tokenizer_diff_test)
 (libraries ounit2 tokenizer_diff)
 (package markup))

(executable
 (name tokenizer_diff_corpus)
 (modules tokenizer_diff_corpus)
 (libraries tokenizer_diff))
