(env
 (afl
  (ocamlopt_flags
   (:standard -afl-instrument -afl-inst-ratio 20))))

(library
 (name markup_lite)
 (public_name markup.lite)
 (synopsis "Small fast synchronous HTML parser")
 (private_modules common error html_parser html_tokenizer html_writer kstream
   namespace text token_source)
 (libraries markup markup.common markup.entities uutf)
 (flags
  (:standard -w -9)))
