(library
 (name performance_common)
 (modules performance_common)
 (libraries unix))

(executable
 (name performance_markup)
 (modules performance_markup)
 (libraries markup performance_common unix))

(executable
 (name performance_corpus)
 (modules performance_corpus)
 (libraries containers markup unix))

(executable
 (name performance_shared_tokenizer)
 (modules performance_shared_tokenizer)
 (libraries containers markup markup.lite unix))

(executable
 (name performance_nethtml)
 (modules performance_nethtml)
 (enabled_if (= %{profile} nethtml))
 (libraries netstring performance_common))

(executable
 (name performance_xmlm)
 (modules performance_xmlm)
 (libraries unix performance_common xmlm))
